services:
  app:
    build:
      context: .
    container_name: home-dashboard
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  news-service:
    build:
      context: ./news_service
    container_name: home-news-service
    env_file:
      - ./news_service/.env
    ports:
      - "8080:8080"
    volumes:
      - ./news_service/data:/app/data
    restart: unless-stopped
